### PR TITLE
Dynamic readme badge

### PR DESCRIPTION
**Pull request by buschtoens**

### CODE REVIEW

**Comment by buschtoens** [comment]
As far as I can see, I didn't produce [this error](https://travis-ci.org/ForbesLindesay/component-website/builds/3481167).

**Comment by ForbesLindesay** [comment]
Yep, that wasn't your fault, it was @kelonye's components which are on the component wiki but don't exist in github.  As for github credentials, see the commit message of https://github.com/ForbesLindesay/component-website/commit/0fdec28c8e8f3ae68b479bd8955fbcd66b83c13a

**Comment by ghost** [comment]
sorry guys renaming stuff here

**Comment by buschtoens** [comment]
No need to be sorry. Seems like we have to refactor our registry so it is fail-safe. ;)

**Comment by ForbesLindesay** [comment]
Yeh, if you look at it now it marks problems in red on that home page, rather than failing to render.  In a sense it was good to spot the error nice and early on, rather than spotting it when there are thousands of components and thousands of users.

**Pull request merged**
