### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by buschtoens**
Added the component logo as a favicon.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Thanks, merged.  There was a slight issue where you'd added `'favicon.ico'` to the path for static files rather than to the `favicon` middleware.  Turns out `favicon` middleware is un-necessary anyway when you put `'favicon.ico'` in the root directory of your static files.  Anyway, fixed by https://github.com/ForbesLindesay/component-website/commit/093ba0383bf5fb9beb85ac76a666ba2d6f9491ae

**Comment by buschtoens** [comment]
Oh yes, I was too confused by all the old code surrounding the stuff I was working on. :D

[`favicon`](http://www.senchalabs.org/connect/favicon.html) isn't completely unnecessary. It caches the favicon so it doesn't have to be read from disk all the time. It also commands the browser to cache the favicon. So it kinda makes sense.

**Comment by buschtoens** [comment]
Please just add this line before the `static`middleware. My git is currently driving me mad.

``` javascript
app.use(express.favicon(path.join(__dirname, 'public', 'favicon.ico')));
```

**Comment by ForbesLindesay** [comment]
Ah, that makes sense, the caching behaviour meant that with the favicon middleware in place I wasn't seeing the updated icon, so I got rid of it.  I've added it back in now with the correct path.

Thanks for the contribution :+1:

**Pull request merged**
